"""
app/api/v1/endpoints/chat.py
=============================
Chat endpoints — the primary user-facing AI interface.

  POST /chat           — send a message, get a response (supports all agents)
  POST /chat/stream    — SSE streaming response
  GET  /conversations  — list conversations
  GET  /conversations/{id} — get conversation with messages
  DELETE /conversations/{id} — archive/delete conversation

FLOW PER REQUEST:
  1. Authenticate user (JWT or API key)
  2. Route to correct agent (rag / gmail / task / router)
  3. Run agent → get LLMResponse + optional sources
  4. Persist conversation + message to PostgreSQL
  5. Write AgentRun metrics record
  6. Return ChatResponse

STREAMING:
  For streaming responses, we use Server-Sent Events (SSE).
  The client receives chunks as they're generated by the LLM.
  We flush the DB write after streaming is complete.
"""

from __future__ import annotations

import time
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.api.v1.dependencies.auth import CurrentUser
from app.core.database import get_db_session
from app.core.logging import get_logger
from app.models.models import AgentRun, Conversation, Message
from app.schemas.schemas import (
    APIResponse,
    ChatRequest,
    ChatResponse,
    PaginatedResponse,
    SourceChunk,
)
from app.services.agents.gmail_agent_2 import GmailAgent
from app.services.agents.rag_agent_2 import RAGAgent
from app.services.agents.router_agent_2 import AgentType, route_query
from app.services.agents.task_agent_2 import TaskAgent
from app.services.llm.router import LLMResponse, llm_router

router = APIRouter(prefix="/chat", tags=["Chat"])
logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Helper: persist conversation + message
# ---------------------------------------------------------------------------

async def _get_or_create_conversation(
    conversation_id: str | None,
    user_id: str,
    agent_type: str,
    db: AsyncSession,
) -> Conversation:
    if conversation_id:
        result = await db.execute(
            select(Conversation)
            .where(Conversation.id == conversation_id)
            .where(Conversation.user_id == user_id)
        )
        conv = result.scalar_one_or_none()
        if not conv:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Conversation not found",
            )
        return conv

    # Create new conversation
    conv = Conversation(
        user_id=user_id,
        agent_type=agent_type,
        title="New conversation",
    )
    db.add(conv)
    await db.flush()
    return conv


async def _save_messages(
    conversation: Conversation,
    user_content: str,
    assistant_content: str,
    llm_resp: LLMResponse,
    sources: list,
    tool_calls: list,
    db: AsyncSession,
) -> Message:
    """Write user + assistant messages to DB. Returns assistant message."""
    # User message
    db.add(Message(
        conversation_id=conversation.id,
        role="user",
        content=user_content,
    ))

    # Assistant message
    assistant_msg = Message(
        conversation_id=conversation.id,
        role="assistant",
        content=assistant_content,
        tokens_used=llm_resp.input_tokens + llm_resp.output_tokens,
        latency_ms=llm_resp.latency_ms,
        model=llm_resp.model,
        provider=llm_resp.provider,
        sources=[
            {"document_id": s.document_id, "filename": s.filename,
             "content": s.content[:500], "score": s.score}
            for s in sources
        ],
        tool_calls=tool_calls,
    )
    db.add(assistant_msg)

    # Update conversation stats
    conversation.total_tokens += llm_resp.input_tokens + llm_resp.output_tokens
    conversation.total_cost_usd += llm_resp.cost_usd
    conversation.model_used = llm_resp.model

    await db.flush()
    return assistant_msg


async def _log_agent_run(
    user_id: str,
    conversation_id: str,
    agent_type: str,
    llm_resp: LLMResponse,
    tool_calls: list,
    success: bool,
    db: AsyncSession,
    error_type: str | None = None,
) -> None:
    """Write an AgentRun telemetry record."""
    db.add(AgentRun(
        user_id=user_id,
        conversation_id=conversation_id,
        agent_type=agent_type,
        input_tokens=llm_resp.input_tokens,
        output_tokens=llm_resp.output_tokens,
        latency_ms=llm_resp.latency_ms,
        provider_used=llm_resp.provider,
        model_used=llm_resp.model,
        was_cached=llm_resp.was_cached,
        used_fallback=llm_resp.used_fallback,
        retry_count=llm_resp.retry_count,
        success=success,
        error_type=error_type,
        tool_calls_made=tool_calls,
        cost_usd=llm_resp.cost_usd,
    ))


# ---------------------------------------------------------------------------
# POST /chat — main chat endpoint
# ---------------------------------------------------------------------------

@router.post(
    "",
    response_model=APIResponse[ChatResponse],
    summary="Send a message to the AI platform",
)
async def chat(
    body: ChatRequest,
    current_user: CurrentUser,
    db: AsyncSession = Depends(get_db_session),
) -> APIResponse[ChatResponse]:
    """
    Unified chat endpoint. Routes to:
      • RAG Agent     — questions answered from uploaded documents
      • Gmail Agent   — email management
      • Task Agent    — natural language task management
      • Router Agent  — auto-detects the right agent
      • Direct        — plain LLM conversation

    Pass agent_type="router" to let the system decide automatically.
    """
    start = time.perf_counter()

    # --- Resolve agent type ---
    agent_type_str = body.agent_type.lower()
    if agent_type_str == "router":
        resolved = await route_query(body.message)
        agent_type_str = resolved.value

    # --- Get or create conversation ---
    conversation = await _get_or_create_conversation(
        body.conversation_id, current_user.id, agent_type_str, db
    )

    # --- Load conversation history for context ---
    if body.conversation_id:
        history_result = await db.execute(
            select(Message)
            .where(Message.conversation_id == conversation.id)
            .order_by(Message.created_at)
        )
        history_messages = [
            {"role": m.role, "content": m.content}
            for m in history_result.scalars().all()
        ]
    else:
        history_messages = []

    sources: list = []
    tool_calls: list = []
    llm_resp: LLMResponse | None = None

    try:
        # --- Dispatch to agent ---
        if agent_type_str == AgentType.RAG:
            rag = RAGAgent()
            llm_resp, search_results = await rag.run(
                query=body.message,
                owner_id=current_user.id,
                conversation_history=history_messages,
                use_cache=not body.stream,
            )
            sources = search_results

        elif agent_type_str == AgentType.GMAIL:
            gmail = GmailAgent(user_id=current_user.id, db=db)
            # Simple routing within the Gmail agent
            message_lower = body.message.lower()
            if "send" in message_lower or "compose" in message_lower:
                # Extract params via LLM then send — simplified here
                content = "Please use the /gmail/send endpoint for sending emails."
                from app.services.llm.router import LLMResponse as LR
                from dataclasses import dataclass
                llm_resp_text = content
            else:
                llm_resp_text = await gmail.summarise_inbox()

            # Wrap in a synthetic LLMResponse
            from dataclasses import dataclass
            from app.services.llm.router import estimate_cost
            llm_resp = LLMResponse(
                content=llm_resp_text,
                provider=llm_router._cache.__class__.__name__,  # just a label
                model="gmail-agent",
                input_tokens=0,
                output_tokens=len(llm_resp_text.split()),
                latency_ms=(time.perf_counter() - start) * 1000,
            )
            # Override with real LLM router call
            llm_resp = await llm_router.complete(
                messages=[*history_messages, {"role": "user", "content": body.message}],
                system=f"You are a Gmail assistant. Context from Gmail: {llm_resp_text}",
            )

        elif agent_type_str == AgentType.TASK:
            task_agent = TaskAgent(user_id=current_user.id, db=db)
            response_text, tool_calls = await task_agent.run(
                instruction=body.message,
                context={"conversation_id": conversation.id},
            )
            llm_resp = await llm_router.complete(
                messages=[{"role": "user", "content": body.message}],
                system="You are a task management assistant. Summarise the result concisely.",
            )
            llm_resp.content = response_text  # Use task agent's response

        else:  # direct
            messages = [*history_messages, {"role": "user", "content": body.message}]
            llm_resp = await llm_router.complete(
                messages=messages,
                system="You are a helpful AI assistant.",
                use_cache=True,
            )

    except Exception as exc:
        logger.error("chat.error", error=str(exc), agent=agent_type_str)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Agent error: {str(exc)}",
        )

    # --- Persist to DB ---
    assistant_msg = await _save_messages(
        conversation=conversation,
        user_content=body.message,
        assistant_content=llm_resp.content,
        llm_resp=llm_resp,
        sources=sources,
        tool_calls=tool_calls,
        db=db,
    )
    await _log_agent_run(
        user_id=current_user.id,
        conversation_id=conversation.id,
        agent_type=agent_type_str,
        llm_resp=llm_resp,
        tool_calls=tool_calls,
        success=True,
        db=db,
    )

    logger.info(
        "chat.complete",
        user_id=current_user.id,
        agent=agent_type_str,
        latency_ms=round(llm_resp.latency_ms, 2),
        tokens=llm_resp.input_tokens + llm_resp.output_tokens,
        cached=llm_resp.was_cached,
    )

    source_chunks = [
        SourceChunk(
            document_id=s.document_id,
            chunk_id=s.weaviate_id,
            filename=s.filename,
            content=s.content,
            score=s.score,
        )
        for s in sources
    ] if body.include_sources else []

    return APIResponse(
        data=ChatResponse(
            conversation_id=conversation.id,
            message_id=assistant_msg.id,
            content=llm_resp.content,
            model_used=llm_resp.model,
            provider_used=llm_resp.provider,
            tokens_used=llm_resp.input_tokens + llm_resp.output_tokens,
            latency_ms=llm_resp.latency_ms,
            was_cached=llm_resp.was_cached,
            used_fallback=llm_resp.used_fallback,
            sources=source_chunks,
            tool_calls=tool_calls,
            created_at=assistant_msg.created_at,
        )
    )


# ---------------------------------------------------------------------------
# POST /chat/stream — Server-Sent Events
# ---------------------------------------------------------------------------

@router.post("/stream", summary="Streaming chat response (SSE)")
async def chat_stream(
    body: ChatRequest,
    current_user: CurrentUser,
) -> StreamingResponse:
    """
    Returns a Server-Sent Events stream.
    Client reads: `data: <chunk>\n\n` and `data: [DONE]\n\n`
    """
    messages = [{"role": "user", "content": body.message}]

    async def event_generator():
        try:
            async for chunk in llm_router.stream(
                messages=messages,
                system="You are a helpful AI assistant.",
            ):
                yield f"data: {chunk}\n\n"
            yield "data: [DONE]\n\n"
        except Exception as exc:
            yield f"data: [ERROR] {str(exc)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",     # Disable nginx buffering for SSE
        },
    )


# ---------------------------------------------------------------------------
# GET /conversations
# ---------------------------------------------------------------------------

@router.get(
    "/conversations",
    response_model=APIResponse[PaginatedResponse],
    summary="List user conversations",
)
async def list_conversations(
    page: int = 1,
    page_size: int = 20,
    current_user: CurrentUser = ...,
    db: AsyncSession = Depends(get_db_session),
) -> APIResponse:
    from sqlalchemy import func

    offset = (page - 1) * page_size
    q = (
        select(Conversation)
        .where(Conversation.user_id == current_user.id)
        .where(Conversation.is_archived == False)  # noqa
        .order_by(Conversation.updated_at.desc())
        .offset(offset)
        .limit(page_size)
    )
    total_q = (
        select(func.count())
        .select_from(Conversation)
        .where(Conversation.user_id == current_user.id)
        .where(Conversation.is_archived == False)  # noqa
    )

    result = await db.execute(q)
    total = (await db.execute(total_q)).scalar_one()
    conversations = result.scalars().all()

    return APIResponse(
        data=PaginatedResponse(
            items=[
                {
                    "id": c.id, "title": c.title, "agent_type": c.agent_type,
                    "model_used": c.model_used, "total_tokens": c.total_tokens,
                    "total_cost_usd": c.total_cost_usd, "updated_at": c.updated_at.isoformat(),
                }
                for c in conversations
            ],
            total=total,
            page=page,
            page_size=page_size,
            pages=(total + page_size - 1) // page_size,
        )
    )


# ---------------------------------------------------------------------------
# GET /conversations/{conversation_id}
# ---------------------------------------------------------------------------

@router.get(
    "/conversations/{conversation_id}",
    summary="Get conversation with full message history",
)
async def get_conversation(
    conversation_id: str,
    current_user: CurrentUser,
    db: AsyncSession = Depends(get_db_session),
) -> APIResponse:
    result = await db.execute(
        select(Conversation)
        .options(selectinload(Conversation.messages))
        .where(Conversation.id == conversation_id)
        .where(Conversation.user_id == current_user.id)
    )
    conv = result.scalar_one_or_none()
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    return APIResponse(
        data={
            "id": conv.id,
            "title": conv.title,
            "agent_type": conv.agent_type,
            "total_tokens": conv.total_tokens,
            "total_cost_usd": conv.total_cost_usd,
            "messages": [
                {
                    "id": m.id, "role": m.role, "content": m.content,
                    "model": m.model, "tokens_used": m.tokens_used,
                    "latency_ms": m.latency_ms, "sources": m.sources,
                    "tool_calls": m.tool_calls, "created_at": m.created_at.isoformat(),
                }
                for m in conv.messages
            ],
        }
    )


# ---------------------------------------------------------------------------
# DELETE /conversations/{conversation_id}
# ---------------------------------------------------------------------------

@router.delete("/conversations/{conversation_id}", response_model=APIResponse)
async def delete_conversation(
    conversation_id: str,
    current_user: CurrentUser,
    db: AsyncSession = Depends(get_db_session),
) -> APIResponse:
    result = await db.execute(
        select(Conversation)
        .where(Conversation.id == conversation_id)
        .where(Conversation.user_id == current_user.id)
    )
    conv = result.scalar_one_or_none()
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")

    conv.is_archived = True
    await db.commit()
    return APIResponse(message="Conversation archived")